# fly.toml app configuration file generated for secret-gift-swap-builder on 2024-11-29T02:19:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'secret-gift-swap-builder'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
